name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if it's not 'main'

permissions:
  contents: write  # Needed for GH Pages deployment to push to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # More reliable in CI than `npm install`

      - name: Build and Export Next.js App
        run: npm run deploy  # This should run `next build && next export`

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages  # Optional: set to the branch you're deploying to
